name: delivery_app
description: A new Flutter application.

version: 1.0.17+18

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  intl: ^0.16.1
  shared_preferences: ^0.5.6+3
  async_loader: ^0.1.2
  location: ^3.0.2
  image_picker: ^0.6.5
  url_launcher: ^5.4.2
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.30
  flutter_polyline_points: ^0.1.0
  toast: ^0.1.5
  getwidget: ^1.1.0
  onesignal_flutter: ^2.4.0
  geocoder: ^0.2.1
  socket_io_client: ^0.9.10
  geolocator: ^6.0.0+1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/watch.png
    - assets/icons/send.png
    - assets/icons/red-pin.png
    - assets/icons/green-pin.png
    - assets/icons/marker.png
    - assets/icons/home.png
    - assets/icons/order.png
    - assets/icons/bell.png
    - assets/icons/right-arrow.png
    - assets/icons/delete.png
    - assets/icons/navigate.png
    - assets/icons/headset.png
    - assets/icons/phone.png
    - assets/icons/cell-phone.png
    - assets/icons/spinner.gif
    - assets/icons/homepin.png
    - assets/icons/agentpin.png
    - assets/icons/storepin.png
    - assets/imgs/ricebowl.png
    - assets/imgs/greenbg.png
    - assets/imgs/logo.png
    - assets/imgs/map.png
    - assets/imgs/dp.png
    - assets/bgs/bg.png
    - assets/imgs/na.jpg
    - assets/i18n/en.json
    - assets/i18n/es.json

  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400

    - family: RobotoLight
      fonts:
        - asset: assets/fonts/RobotoLight.ttf
          weight: 400

    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 400

    - family: RobotoBold
      fonts:
        - asset: assets/fonts/RobotoBold.ttf
          weight: 400
